### ISSUE TITLE
Проверка лабораторной работы 5

### ISSUE THREAD

**Issue by dragoblued** [dragoblued/lab5#1]
Выполнила:
Табаева Н.А.

To: @evgeny-p

**Comment by dragoblued** [comment]
редактировала

**Comment by evgeny-p** [comment]
Для временных файлов в `.gitignore` можно записать единственную маску: `*~`.

**Comment by dragoblued** [comment]
Исправила

**Comment by dragoblued** [comment]
Исправила.

**Comment by evgeny-p** [comment]
Принято.
